# Change these first
owner: KaratekHD # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Homepage
    url: https://karatek.net
  - name: IServ
    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.karatek.systems
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /status
  logoUrl: https://karatek.net/img/logo.png
  name: Karatek Monitor Page
  introTitle: "This is the **Karatek Monitor**."
  introMessage: It shows the uptime of some **external** services I'd like to monitor. If you want me to add something here, feel free to drop me a line, see my [contact page](https://karatek.net/Legal/contact/)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
